version: "3.9"
services:
  postgres:
    hostname: event_sourcing_db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    restart: unless-stopped
  mongo:
    build:
      context: mongoDb
      dockerfile: /Dockerfile
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  postgres_projections:
    hostname: event_sourcing_db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}_projections
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT_PROJECTIONS}:5432
    restart: unless-stopped
volumes:
  mongo_data: { }
